server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:example@cluster0.0wchj.mongodb.net/test?retryWrites=true&w=majority
#      uri: mongodb://root:example@192.168.99.100:27017/test?authSource=admin&authMechanism=SCRAM-SHA-1&replicaSet=rs0


#spring:
#  data:
#    mongodb:
#      database: test
#      port: 27017
#      host: 192.168.99.100
#      username: root
#      password: example
#      authentication-database: admin
#      replica-set-name: rs0
